apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sure-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - account.limtaehyun.dev
      secretName: tls
  rules:
    - host: account.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sure-service
                port:
                  number: 3000
