apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sure-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - account.limtaehyun.dev
      secretName: sure-tls
  rules:
    - host: account.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sure-service
                port:
                  number: 3000
