apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: couchdb
spec:
  hosts:
    - "couchdb.lth.so"
    - "couchdb.limtaehyun.dev"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - headers:
            :authority:
              exact: couchdb.limtaehyun.dev
      redirect:
        authority: couchdb.lth.so
    - route:
        - destination:
            host: couchdb-service.couchdb.svc.cluster.local
            port:
              number: 5984
