apiVersion: v1
kind: Service
metadata:
  name: termix-service
spec:
  selector:
    app: termix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081
