apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentik
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - authentik
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
