apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technitium
  template:
    metadata:
      labels:
        app: technitium
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: server
          image: technitium/dns-server:latest
          ports:
            - containerPort: 5380
            - containerPort: 53
          env:
            - name: DNS_SERVER_DOMAIN
              value: dns-server
            - name: DNS_SERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: technitium-secret
                  key: DNS_SERVER_ADMIN_PASSWORD
          volumeMounts:
            - name: technitium-data
              mountPath: /etc/dns
      volumes:
        - name: technitium-data
          persistentVolumeClaim:
            claimName: technitium-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium-prometheus-exporter
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technitium-prometheus-exporter
  template:
    metadata:
      labels:
        app: technitium-prometheus-exporter
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: server
          image: ghcr.io/brioche-works/technitium-dns-prometheus-exporter:master
          ports:
            - containerPort: 8080
          env:
            - name: TECHNITIUM_API_DNS_BASE_URL
              value: http://technitium-service.technitium.svc.cluster.local:5380
            - name: TECHNITIUM_API_DNS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: technitium-secret
                  key: DNS_API_TOKEN
            - name: TECHNITIUM_API_DNS_LABEL
              value: "dns"
