apiVersion: v1
kind: Service
metadata:
  name: technitium-service
spec:
  selector:
    app: technitium
  ports:
    - name: admin
      protocol: TCP
      port: 5380
      targetPort: 5380
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
