apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: authentik
spec:
  hosts:
    - "auth.lth.so"
    - "auth.limtaehyun.dev"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - headers:
            :authority:
              exact: auth.limtaehyun.dev
      redirect:
        authority: auth.lth.so
    - route:
        - destination:
            host: authentik-service.authentik.svc.cluster.local
            port:
              number: 9000
