apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ./pv.yml
  - ./pvc.yml
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./rbac.yml
  - ./virtual-service.yml
  - ./virtual-service/n8n.yml
  - ./virtual-service/bridge.yml
  - ./virtual-service/technitium.yml
