apiVersion: v1
kind: Service
metadata:
  name: authentik-service
  labels:
    app.kubernetes.io/name: authentik-service
    app.kubernetes.io/part-of: authentik
spec:
  selector:
    app: authentik-server
  ports:
    - name: web
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: metrics
      protocol: TCP
      port: 9300
      targetPort: 9300