apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-doh-ingress
  namespace: adguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - adguard.limtaehyun.dev
      secretName: adguard-tls
  rules:
    - host: adguard.limtaehyun.dev
      http:
        paths:
          - path: /dns-query
            pathType: Prefix
            backend:
              service:
                name: adguard-service
                port:
                  number: 443
