apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
  namespace: authentik
spec:
  ingressClassName: nginx
  rules:
    - host: adguard.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-proxy
                port:
                  number: 9000
