apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard
resources:
  - ./deployment.yml
  - ./pv.yml
  - ./pvc.yml
  - ./service.yml
  - ./virtual-service.yml
  - ./destination-rule.yml
