apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: clickhouse/clickhouse-server:latest
          ports:
            - containerPort: 9000
            - containerPort: 8123
            - containerPort: 9440
            - containerPort: 9009
          env:
            - name: CLICKHOUSE_USER
              value: admin
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: adminPassword
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-storage
      volumes:
        - name: couchdb-storage
          persistentVolumeClaim:
            claimName: couchdb-pvc
