apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
  - ./gateway.yml
  - ./redirect-limtaehyun.yml
  - ./argocd-virtual-service.yml
  - ./argocd-destination-rule.yml