apiVersion: apps/v1
kind: Deployment
metadata:
  name: badges
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: badges
  template:
    metadata:
      labels:
        app: badges
        app.kubernetes.io/version: v1
    spec:
      serviceAccountName: badges
      containers:
        - name: badges
          image: ghcr.io/noeulnight/kube-badges:latest
          ports:
            - containerPort: 3000
