apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: badges
spec:
  ingressClassName: nginx
  rules:
    - host: "badges.limtaehyun.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: badges
                port:
                  number: 80
