apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: badges
resources:
  - ./cluster-role-binding.yml
  - ./cluster-role.yml
  - ./deployment.yml
  - ./service.yml
  - ./service-account.yml
  - ./virtual-service.yml
