apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-server
  template:
    metadata:
      labels:
        app: spotify-server
    spec:
      containers:
        - name: server
          image: ghcr.io/noeulnight/sspotify_server
          ports:
            - containerPort: 8080
          env:
            - name: API_ENDPOINT
              value: https://spotify.limtaehyun.dev/api
            - name: CLIENT_ENDPOINT
              value: https://spotify.limtaehyun.dev
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: spotify-secret
                  key: SPOTIFY_PUBLIC
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-secret
                  key: SPOTIFY_SECRET
            - name: TIMEZONE
              value: Asia/Seoul
            - name: MONGO_ENDPOINT
              value: mongodb://mongo-service.mongo.svc.cluster.local:27017/your_spotify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-web
  template:
    metadata:
      labels:
        app: spotify-web
    spec:
      containers:
        - name: web
          image: ghcr.io/noeulnight/sspotify_client
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: https://spotify.limtaehyun.dev/api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-canvas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-canvas-api
  template:
    metadata:
      labels:
        app: spotify-canvas-api
    spec:
      containers:
        - name: web
          image: ghcr.io/noeulnight/spotify-canvas-api
          ports:
            - containerPort: 3000
          env:
            - name: SPOTIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spotify-canvas-secret
                  key: SPOTIFY_TOKEN
            - name: REDIS_HOST
              value: redis-service.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "3"
            - name: NODE_ENV
              value: production
            - name: NODE_OPTIONS
              value: "--dns-result-order=ipv4first"
