apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spotify
resources:
  - ./secret.yml
  - ./webfinger.yml
  - ./connector.yml
  - ./server-deployment.yml
  - ./server-service.yml
  - ./web-deployment.yml
  - ./web-service.yml
  - ./ingress.yml
