apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-web
  template:
    metadata:
      labels:
        app: spotify-web
    spec:
      containers:
        - name: web
          image: yooooomi/your_spotify_client
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: https://spotify.limtaehyun.dev/api
