apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./virtual-service.yml
  - ./pvc.yml
  - ./pv.yml
  - ./waypoint.yml
