apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wakapi
  template:
    metadata:
      labels:
        app: wakapi
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: wakapi
          image: ghcr.io/muety/wakapi:latest
          ports:
            - containerPort: 3000
          env:
            - name: WAKAPI_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: WAKAPI_PASSWORD_SALT
            - name: WAKAPI_DB_TYPE
              value: postgres
            - name: WAKAPI_DB_HOST
              value: postgres-service.postgres.svc.cluster.local
            - name: WAKAPI_DB_PORT
              value: "5432"
            - name: WAKAPI_DB_USER
              value: wakapi
            - name: WAKAPI_DB_NAME
              value: wakapi
            - name: WAKAPI_ALLOW_SIGNUP
              value: "false"
            - name: WAKAPI_OIDC_ALLOW_SIGNUP
              value: "true"
            - name: WAKAPI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: WAKAPI_DB_PASSWORD
            - name: WAKAPI_OIDC_PROVIDERS_0_NAME
              value: authentik
            - name: WAKAPI_OIDC_PROVIDERS_0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: WAKAPI_OIDC_CLIENT_ID
            - name: WAKAPI_OIDC_PROVIDERS_0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: WAKAPI_OIDC_CLIENT_SECRET
            - name: WAKAPI_OIDC_PROVIDERS_0_ENDPOINT
              value: https://auth.lth.so/application/o/wakatime/
            - name: WAKAPI_PUBLIC_URL
              value: https://wakatime.lth.so
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wakapi-pvc
