apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: wakapi
spec:
  hosts:
    - "wakatime.lth.so"
    - "wakatime.limtaehyun.dev"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - headers:
            :authority:
              exact: wakatime.limtaehyun.dev
      redirect:
        authority: wakatime.lth.so
    - route:
        - destination:
            host: wakapi-service.wakapi.svc.cluster.local
            port:
              number: 3000
