apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "*"
      helm:
        releaseName: istio-ingress
        values: |
          service:
            type: LoadBalancer
          volumes:
            - name: envoy-lua-script
              secret:
                secretName: envoy-lua-script
                defaultMode: 0444
          volumeMounts:
            - name: envoy-lua-script
              mountPath: /etc/envoy-filter
              readOnly: true

    - path: istio-ingress
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
