apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affine-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - document.limtaehyun.dev
      secretName: limtaehyun-dev-tls
  rules:
    - host: document.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: affine-service
                port:
                  number: 3010
