apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visualizer-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - visualizer.limtaehyun.dev
      secretName: limtaehyun-dev-tls
  rules:
    - host: visualizer.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualizer-service
                port:
                  number: 8000
