apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - coder.limtaehyun.dev
      secretName: tls
  rules:
    - host: coder.limtaehyun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coder-service
                port:
                  number: 80
